# Generated by Django 5.1.1 on 2024-10-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок сайта')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип')),
                ('facebook', models.URLField(verbose_name='Ссылка, на facebook')),
                ('instagram', models.URLField(verbose_name='Ссылка, на instagram')),
                ('twitter', models.URLField(verbose_name='Ссылка, на twitter')),
                ('github', models.URLField(verbose_name='Ссылка, на github')),
                ('google', models.URLField(verbose_name='Ссылка, на google')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
