# Generated by Django 5.1.2 on 2024-10-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок блога')),
                ('description', models.TextField(verbose_name='Описание блога')),
                ('image', models.ImageField(upload_to='image_blog/', verbose_name='Изображение блога')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации блога')),
                ('coment', models.CharField(max_length=255, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя сотрудника')),
                ('photo', models.ImageField(upload_to='image/', verbose_name='Фото сотрудника')),
                ('position', models.CharField(max_length=255, verbose_name='Должность сотрудника')),
                ('facebook', models.URLField(verbose_name='Ссылка на facebook')),
                ('twitter', models.URLField(verbose_name='Ссылка на twitter')),
                ('github', models.URLField(verbose_name='Ссылка на Github')),
                ('google', models.URLField(verbose_name='Ссылка на Google +')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AlterModelOptions(
            name='basesettings',
            options={'verbose_name': 'Основная настройка сайта', 'verbose_name_plural': 'Основные настройки сайта'},
        ),
        migrations.RemoveField(
            model_name='basesettings',
            name='instagram',
        ),
        migrations.AlterField(
            model_name='basesettings',
            name='facebook',
            field=models.URLField(verbose_name='Ссылка на facebook'),
        ),
        migrations.AlterField(
            model_name='basesettings',
            name='github',
            field=models.URLField(verbose_name='Ссылка на Github'),
        ),
        migrations.AlterField(
            model_name='basesettings',
            name='google',
            field=models.URLField(verbose_name='Ссылка на Google +'),
        ),
        migrations.AlterField(
            model_name='basesettings',
            name='logo',
            field=models.ImageField(upload_to='logo/', verbose_name='Логотип сайта'),
        ),
        migrations.AlterField(
            model_name='basesettings',
            name='twitter',
            field=models.URLField(verbose_name='Ссылка на twitter'),
        ),
    ]
